let a = 10; 
try{
    c=a+b ;
    console.log(c);
}catch (err){
    console.log(err);
}
// try block is used to test a block of code for errors.
// catch block is used to handle the error.